# Generated by Django 3.1.3 on 2020-11-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('orderID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('orderDate', models.DateField()),
                ('deadline', models.DateField()),
                ('backlog', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('pending', 'PENDING'), ('backlog', 'BACKLOG'), ('running', 'RUNNING'), ('completed', 'COMPLETED')], default='pending', max_length=20)),
                ('Model1', models.CharField(default='', max_length=10)),
                ('Quantity1', models.IntegerField(default=0)),
                ('Model2', models.CharField(blank=True, default='', max_length=10)),
                ('Quantity2', models.IntegerField(blank=True, default=0)),
                ('Model3', models.CharField(blank=True, default='', max_length=10)),
                ('Quantity3', models.IntegerField(blank=True, default=0)),
                ('Model4', models.CharField(blank=True, default='', max_length=10)),
                ('Quantity4', models.IntegerField(blank=True, default=0)),
                ('Model5', models.CharField(blank=True, default='', max_length=10)),
                ('Quantity5', models.IntegerField(blank=True, default=0)),
                ('Model6', models.CharField(blank=True, default='', max_length=10)),
                ('Quantity6', models.IntegerField(blank=True, default=0)),
                ('Model7', models.CharField(blank=True, default='', max_length=10)),
                ('Quantity7', models.IntegerField(blank=True, default=0)),
                ('Model8', models.CharField(blank=True, default='', max_length=10)),
                ('Quantity8', models.IntegerField(blank=True, default=0)),
                ('Model9', models.CharField(blank=True, default='', max_length=10)),
                ('Quantity9', models.IntegerField(blank=True, default=0)),
                ('Model10', models.CharField(blank=True, default='', max_length=10)),
                ('Quantity10', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
