# Generated by Django 3.1.3 on 2020-11-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Model1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model10',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model6',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model7',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model8',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model9',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Quantity1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Quantity10',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Quantity2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Quantity3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Quantity4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Quantity5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Quantity6',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Quantity7',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Quantity8',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Quantity9',
        ),
    ]
