# Generated by Django 3.1.3 on 2020-11-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_order_suit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Model1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model10',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model6',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model7',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model8',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Model9',
        ),
        migrations.RemoveField(
            model_name='order',
            name='suit',
        ),
        migrations.AddField(
            model_name='order',
            name='Laptop1',
            field=models.IntegerField(choices=[(1, 'Model1'), (2, 'Model2'), (3, 'Model3'), (4, 'Model4'), (5, 'Model5'), (6, 'Model6'), (7, 'Model7'), (8, 'Model8'), (9, 'Model9'), (10, 'Model10')], default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='Laptop10',
            field=models.IntegerField(choices=[(1, 'Model1'), (2, 'Model2'), (3, 'Model3'), (4, 'Model4'), (5, 'Model5'), (6, 'Model6'), (7, 'Model7'), (8, 'Model8'), (9, 'Model9'), (10, 'Model10')], default=10),
        ),
        migrations.AddField(
            model_name='order',
            name='Laptop2',
            field=models.IntegerField(choices=[(1, 'Model1'), (2, 'Model2'), (3, 'Model3'), (4, 'Model4'), (5, 'Model5'), (6, 'Model6'), (7, 'Model7'), (8, 'Model8'), (9, 'Model9'), (10, 'Model10')], default=2),
        ),
        migrations.AddField(
            model_name='order',
            name='Laptop3',
            field=models.IntegerField(choices=[(1, 'Model1'), (2, 'Model2'), (3, 'Model3'), (4, 'Model4'), (5, 'Model5'), (6, 'Model6'), (7, 'Model7'), (8, 'Model8'), (9, 'Model9'), (10, 'Model10')], default=3),
        ),
        migrations.AddField(
            model_name='order',
            name='Laptop4',
            field=models.IntegerField(choices=[(1, 'Model1'), (2, 'Model2'), (3, 'Model3'), (4, 'Model4'), (5, 'Model5'), (6, 'Model6'), (7, 'Model7'), (8, 'Model8'), (9, 'Model9'), (10, 'Model10')], default=4),
        ),
        migrations.AddField(
            model_name='order',
            name='Laptop5',
            field=models.IntegerField(choices=[(1, 'Model1'), (2, 'Model2'), (3, 'Model3'), (4, 'Model4'), (5, 'Model5'), (6, 'Model6'), (7, 'Model7'), (8, 'Model8'), (9, 'Model9'), (10, 'Model10')], default=5),
        ),
        migrations.AddField(
            model_name='order',
            name='Laptop6',
            field=models.IntegerField(choices=[(1, 'Model1'), (2, 'Model2'), (3, 'Model3'), (4, 'Model4'), (5, 'Model5'), (6, 'Model6'), (7, 'Model7'), (8, 'Model8'), (9, 'Model9'), (10, 'Model10')], default=6),
        ),
        migrations.AddField(
            model_name='order',
            name='Laptop7',
            field=models.IntegerField(choices=[(1, 'Model1'), (2, 'Model2'), (3, 'Model3'), (4, 'Model4'), (5, 'Model5'), (6, 'Model6'), (7, 'Model7'), (8, 'Model8'), (9, 'Model9'), (10, 'Model10')], default=7),
        ),
        migrations.AddField(
            model_name='order',
            name='Laptop8',
            field=models.IntegerField(choices=[(1, 'Model1'), (2, 'Model2'), (3, 'Model3'), (4, 'Model4'), (5, 'Model5'), (6, 'Model6'), (7, 'Model7'), (8, 'Model8'), (9, 'Model9'), (10, 'Model10')], default=8),
        ),
        migrations.AddField(
            model_name='order',
            name='Laptop9',
            field=models.IntegerField(choices=[(1, 'Model1'), (2, 'Model2'), (3, 'Model3'), (4, 'Model4'), (5, 'Model5'), (6, 'Model6'), (7, 'Model7'), (8, 'Model8'), (9, 'Model9'), (10, 'Model10')], default=9),
        ),
    ]
