# Generated by Django 3.1.3 on 2020-11-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0005_auto_20201118_0127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='type',
            new_name='status',
        ),
    ]
