# Generated by Django 3.1.3 on 2020-11-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_auto_20201119_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderID',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
