# Generated by Django 3.1.3 on 2020-11-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0012_auto_20201119_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Laptop1',
            field=models.IntegerField(choices=[(1, 'Xps 13'), (2, 'Xps 15'), (3, 'Inspiron 3567'), (4, 'Inspiron 5379'), (5, 'Inspiron 7567'), (6, 'Vostro 3568'), (7, 'Vostro 5370'), (8, 'Latitude 5480'), (9, 'Alienware 15'), (10, 'Alienware 17')], default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='Laptop10',
            field=models.IntegerField(choices=[(1, 'Xps 13'), (2, 'Xps 15'), (3, 'Inspiron 3567'), (4, 'Inspiron 5379'), (5, 'Inspiron 7567'), (6, 'Vostro 3568'), (7, 'Vostro 5370'), (8, 'Latitude 5480'), (9, 'Alienware 15'), (10, 'Alienware 17')], default=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='Laptop2',
            field=models.IntegerField(choices=[(1, 'Xps 13'), (2, 'Xps 15'), (3, 'Inspiron 3567'), (4, 'Inspiron 5379'), (5, 'Inspiron 7567'), (6, 'Vostro 3568'), (7, 'Vostro 5370'), (8, 'Latitude 5480'), (9, 'Alienware 15'), (10, 'Alienware 17')], default=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='Laptop3',
            field=models.IntegerField(choices=[(1, 'Xps 13'), (2, 'Xps 15'), (3, 'Inspiron 3567'), (4, 'Inspiron 5379'), (5, 'Inspiron 7567'), (6, 'Vostro 3568'), (7, 'Vostro 5370'), (8, 'Latitude 5480'), (9, 'Alienware 15'), (10, 'Alienware 17')], default=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='Laptop4',
            field=models.IntegerField(choices=[(1, 'Xps 13'), (2, 'Xps 15'), (3, 'Inspiron 3567'), (4, 'Inspiron 5379'), (5, 'Inspiron 7567'), (6, 'Vostro 3568'), (7, 'Vostro 5370'), (8, 'Latitude 5480'), (9, 'Alienware 15'), (10, 'Alienware 17')], default=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='Laptop5',
            field=models.IntegerField(choices=[(1, 'Xps 13'), (2, 'Xps 15'), (3, 'Inspiron 3567'), (4, 'Inspiron 5379'), (5, 'Inspiron 7567'), (6, 'Vostro 3568'), (7, 'Vostro 5370'), (8, 'Latitude 5480'), (9, 'Alienware 15'), (10, 'Alienware 17')], default=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='Laptop6',
            field=models.IntegerField(choices=[(1, 'Xps 13'), (2, 'Xps 15'), (3, 'Inspiron 3567'), (4, 'Inspiron 5379'), (5, 'Inspiron 7567'), (6, 'Vostro 3568'), (7, 'Vostro 5370'), (8, 'Latitude 5480'), (9, 'Alienware 15'), (10, 'Alienware 17')], default=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='Laptop7',
            field=models.IntegerField(choices=[(1, 'Xps 13'), (2, 'Xps 15'), (3, 'Inspiron 3567'), (4, 'Inspiron 5379'), (5, 'Inspiron 7567'), (6, 'Vostro 3568'), (7, 'Vostro 5370'), (8, 'Latitude 5480'), (9, 'Alienware 15'), (10, 'Alienware 17')], default=7),
        ),
        migrations.AlterField(
            model_name='order',
            name='Laptop8',
            field=models.IntegerField(choices=[(1, 'Xps 13'), (2, 'Xps 15'), (3, 'Inspiron 3567'), (4, 'Inspiron 5379'), (5, 'Inspiron 7567'), (6, 'Vostro 3568'), (7, 'Vostro 5370'), (8, 'Latitude 5480'), (9, 'Alienware 15'), (10, 'Alienware 17')], default=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='Laptop9',
            field=models.IntegerField(choices=[(1, 'Xps 13'), (2, 'Xps 15'), (3, 'Inspiron 3567'), (4, 'Inspiron 5379'), (5, 'Inspiron 7567'), (6, 'Vostro 3568'), (7, 'Vostro 5370'), (8, 'Latitude 5480'), (9, 'Alienware 15'), (10, 'Alienware 17')], default=9),
        ),
    ]
