# Generated by Django 3.1.3 on 2020-11-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0013_auto_20201119_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('laptopID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=20)),
                ('step1', models.IntegerField(default=0)),
                ('step2', models.IntegerField(default=0)),
                ('step3', models.IntegerField(default=0)),
                ('colour', models.CharField(max_length=10)),
            ],
        ),
    ]
