# Generated by Django 3.1.3 on 2020-11-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0014_laptop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptop',
            name='colour',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='name',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='step1',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='step2',
        ),
        migrations.RemoveField(
            model_name='laptop',
            name='step3',
        ),
    ]
