# Generated by Django 3.1.3 on 2020-11-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0018_auto_20201121_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
