# Generated by Django 3.1.3 on 2020-11-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0019_auto_20201121_0212'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='link',
            field=models.CharField(default='', max_length=200),
        ),
    ]
